### PR TITLE
Separate messages + GUI packages

### PR DESCRIPTION
**Pull request by xqms**
See #70 for rationale.

New package layout:
* `rosmon_msgs` for message definitions
* `rosmon_gui` for the GUI, depending on `rosmon_msgs`
* `rosmon` for `rosmon` itself, depending on `rosmon_msgs`

People using the rqt GUI will need to install the additional `rosmon_gui` package, but I think this is justifiable - it's mostly humans using the GUI, and they will notice if it is not available anymore.

The alternative of having a `rosmon_core` package with the `rosmon` node is a) much more work (all of the unit tests etc refer to the rosmon package) and can b) easily break existing setups which expect `rosmon` in package `rosmon`.

**TODO**:

- [x] Think again about the split into a metapackage and a `rosmon-core` package containing the node. In this case, we would need some proxy nodes inside the otherwise empty `rosmon` package to keep legacy codebases working.
- [x] Do other renames (`rqt_rosmon`)
- [ ] Test this carefully in several of our "production" setups, also at least once with built Debian packages - it is easy to mess something up here.

### CODE REVIEW

**Comment by romainreignier** [comment]
You could create a metapackage to install all packages in one call. But I do not have any idea for the name and not sure if it is really useful.

**Comment by romainreignier** [comment]
`rosmon_gui` still uses `rosmon` namespace internally (in C++ it's Ok, but maybe change `rqt_plugin.xml` file) so the  the rqt plugin is named `rosmon/MonGui` while I was looking for a `rosmon_gui/MonGui`.

On the same subject, I would prefer to rename it `rqt_rosmon` to be aligned with the other rqt plugins.

A `rosmon_gui` script file to start rosmon_gui directly with `rosrun rosmon_gui rosmon_gui` would be nice.

```Python
#!/usr/bin/env python

import sys

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone='rosmon/MonGUI'))
```

**But** `rosrun rqt_rosmon rqt_rosmon` would be even nicer.

Anyway, from my tests, the rqt plugins do not show any running process while I can see them with `rostopic echo /rosmon_1549273214446106912/state`.

**Comment by romainreignier** [comment]
Yeah! You found it! I was about to propose a patch :+1:

**Comment by romainreignier** [comment]
So now the rqt plugin works.

**Comment by xqms** [comment]
Yep, that was the cause. Sadly, we don't have unit tests on the GUI...

I think your proposed rename to `rqt_gui` is a good idea and this would be an appropriate time to do it. I'll probably get around to this later today.

**Comment by romainreignier** [comment]
Hi,
Do you need any help on finishing this PR?

Also, a new Melodic sync has just been frozen, so it will be for the next but it would be nice to release the *wait roscore* and *flush stdout* features released.
But because the behavior is a bit different, maybe it's better to wait for this PR merged and release a new major version.

**Comment by xqms** [comment]
Hey, I kind of lost track of this PR because of the IROS conference deadline - but I'm free to work on it again now.

I'll modify the PR description above with my TODO. If you want to collaborate on this, feel free to pick something :-)

**Comment by xqms** [comment]
I think the main parts are implemented now and the unit tests pass. I decided in favor of the "empty" `rosmon` package which depends on `rosmon_core`, with a proxy script in `rosmon` so that `rosrun rosmon rosmon ...` still works.

I'm now trying to convince `generate_release_script.py` from `ros_buildfarm` to build this branch so that we get some testable deb packages...

**Comment by xqms** [comment]
It seems the best way to test the Debian package is to actually release and use the `ros-shadow-fixed` to test it. I'll test things locally (built from source) in some of our workspaces and then probably perform a release into melodic tomorrow.

**Comment by romainreignier** [comment]
I was testing this branch today on our real robot and it was ok.
But not retro-compatible with the old version of the rqt plugin, but it's ok.

**Comment by xqms** [comment]
In our workspaces everything seems to work, so I merged this PR. Further discussion should move to #72.

**Comment by xqms** [comment]
... should move to #70.

**Pull request merged**
