### PR TITLE
core: logger: Use append mode for log file

### PR DESCRIPTION
**Pull request by amilcarlucas**
…utputted logfile

This needs some testing yet.

I am using this together with this logrotate file: 
```
copytruncate
nocompress
notifempty
olddir
/tmp/ros-*.log {
    sharedscripts
    postrotate
        pkill -SIGUSR1 "rosmon$"
    endscript
}
```

### CODE REVIEW

**Comment by xqms** [comment]
Hey, thanks for the PR!

I think from reading the linked stackoverflow posts that it should be enough to open the file with `O_APPEND` - maybe we should just switch to that instead of trying to detect that a truncation has happened.

Also, accessing `m_file->_fileno` is really unportable, we should at least use `fileno(m_file)`.

**Comment by xqms** [comment]
The cleanest solution is probably to support the `SIGHUP` signal, which is usually used to signal log-generating processes that they should re-open the log file. That way, no data can be lost.

An alternative would be to integrate with the `systemd` journal framework and just use that for logging - it can handle log rotation / deletion natively.

**Comment by amilcarlucas** [comment]
Thanks, I just changed the patch

**Comment by xqms** [comment]
I removed the commented code and squashed the commits. Almost ready for merging, but somehow the CI does not work... I will need to investigate this tomorrow.

**Comment by amilcarlucas** [comment]
I tested the changes and they do not work, the log still does not get properly truncated :(

**Comment by amilcarlucas** [comment]
This s a new attempt, still untested.

**Comment by amilcarlucas** [comment]
It works fine :) But it is more complex than the append solution. I need to test the append solution again.

**Comment by xqms** [comment]
Since #172 has landed, your issue should be addressed by switching to `--log=syslog`. Therefore I'll close this.

**Pull request closed without merging**
